apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: nonroot
spec:
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: MustRunAsNonRoot
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  volumes:
  - '*'