apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp-all
rules:
- apiGroups: ["extensions"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: psp-student
subjects:
- kind: User
  name: student
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: kubernetes-admin
  apiGroup: rbac.authorization.k8s.io 
- kind: Group
  name: system:serviceaccounts:kube-system
  apiGroup: rbac.authorization.k8s.io
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: psp-all
