apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resource
  namespace: default
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 1Gi