kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: super-secret
  namespace: default
  labels:
    lab: authz
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["super-secret"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: super-secret
  labels:
    lab: authz
subjects:
- kind: User
  name: student
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: super-secret
  apiGroup: rbac.authorization.k8s.io