apiVersion: v1
kind: Pod
metadata:
  name: centos
spec:
  containers:
    - name: centos
      image: centos:7
      args: [bash, -c, 'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 100; done']
      resource: